
services:

  database:
    container_name: clinic-database
    hostname: database
    restart: always
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: admin
      POSTGRES_DB: admin
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data

  meilisearch:
    container_name: clinic-meilisearch
    image: getmeili/meilisearch:v1.23.0
    ports:
      - 7700:7700
    volumes:
      - ./meili_data:/meili_data
