
services:

  database:
    container_name: clinic-database
    hostname: database
    restart: always
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: admin
      POSTGRES_DB: admin
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data


